# Default values for electrical-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: "electrical-api"
replicaCount: 1

# Default Settings for the API
image:
  repository: coengineercontainerregistry.azurecr.io/coengineer/electrical-api
  tag: latest # Jenkins replaces latest with specific container version
  pullPolicy: Always

service:
  type: ClusterIP
  clusterPort: 8080 # Expose port from kubernetes cluster. The ingress will be seeing this
  containerPort: 8080 # Target container port or image port. See reference/pod.md on how to check the listening port of pod

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-issuer"  # Make sure the issuer is installed
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 16m
  ingressClassName: nginx
  host: electrical-api.dev.coengineer.com.au
  hostPath: /
  tls:
    enabled: true
    secretName: letsencrypt-tls # Make sure the TLS Certificate is created prior to installing the info

configmap:
  environment: "Development" # Lets leave it as production foreach environment, if you need it, adjust it
  dbConnectionString: "<redacted>"
  apiCors: "https://*.coengineer.com.au"

secret:
  testSecret: PGJhc2U2NCBlbmNvZGVkPgo= # (<base64 encoded>)

# Set the resources consumption
# resources:
#   requests:
#     cpu: 500m
#     memory: 128Mi
#   limits:
#     cpu: 750m
#     memory: 256Mi

readinessProbe:
  enabled: true
  initialDelaySeconds: 20
  periodSeconds: 10
  timeoutSeconds: 1
  failureThreshold: 3

livenessProbe:
  enabled: true
  initialDelaySeconds: 120
  periodSeconds: 20
  timeoutSeconds: 1
  failureThreshold: 3

nodeSelector: {}

tolerations: []

affinity: {}
