name: publish-to-acr

on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: "The environment to run the workflow."
        default: 'development'
      image_tag:
        type: string
        description: "The image tag or fullname with version to push in acr."
        required: true
      workspace:
        type: string
        description: "The image workspace to build"
        required: true
      dockerfile_path:
        type: string
        description: "The dockerfile path."

jobs:
  # Publish artifacts to ACR
  publish-to-acr:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:

    - uses: actions/checkout@v3

    - run: echo ${GITHUB_REF_NAME}

    - name: "Download artifacts"
      if: ${{ inputs.workspace == 'api' }}
      uses: actions/download-artifact@v3
      with:
        name: api_workspace
        path: out

    - name: "Download artifacts"
      if: ${{ inputs.workspace == 'web' }}
      uses: actions/download-artifact@v3
      with:
        name: web_workspace
        path: icmd-main/Frontend/dist

    - name: "Azure login"
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Builds and pushes an image up to your Azure Container Registry
    - name: "Build and push image to ACR"
      run: |
        az acr build --image ${{ inputs.image_tag }} \
        --registry ${{ vars.AZURE_ACR_SHARED }} -g ${{ vars.AZURE_RG_SHARED }} \
        --file ${{ inputs.dockerfile_path }} .
