name: "scheduled-cleanup"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * 1" # every monday night at 1 am UTC

jobs:
  clear-artifacts:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: 0 # Set this to 0 to delete all artifacts
