name: build-and-upload

on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: "Environment to run the workflow."
        default: "development"
      image_version:
        type: string
        description: "Version of the Docker image."
        required: true

  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: "Environment to run the workflow."
        default: "development"
      image_version:
        type: string
        description: "Version of the Docker image."
        required: true

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:

    - uses: actions/checkout@v3

    - run: echo ${GITHUB_REF#refs/*/}

    - name: Use Node
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
        cache-dependency-path: icmd-main/Frontend/yarn.lock

    - name: Install dependencies
      run: yarn --cwd $(pwd)/icmd-main/Frontend install

    - name: Build development environment
      if: ${{ inputs.environment == 'development' }}
      run: yarn --cwd $(pwd)/icmd-main/Frontend electrical:publish:dev

    - name: Build production environment
      if: ${{ inputs.environment == 'production' }}
      run: yarn --cwd $(pwd)/icmd-main/Frontend electrical:publish:prod

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: web_workspace
        path: icmd-main/Frontend/dist
