apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.configmap" . }}
  labels:
    app: {{ include "app.name" . }}
    chart: {{ include "app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  ASPNETCORE_ENVIRONMENT: {{ .Values.configmap.environment | quote }}
  DB_CONNECTION_STRING: {{ .Values.configmap.dbConnectionString | quote }}
  API_CORS: {{ .Values.configmap.apiCors | quote }}
