apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.secret" . }}
  labels:
    app: {{ include "app.name" . }}
    chart: {{ include "app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  testSecret: {{ .Values.secret.testSecret | quote }}
